name: Aplicação - CI/CD

on:
  push:
    branches:
      - main
      - feature-flask-app

jobs:
  remote-pipeline:
    uses: Nicolascf/shared-libraries/.github/workflows/flask-app-deploy-local.yml@feature-pipeline  # Chama a Golden Pipeline
    with:
      service_name: "Flask-App-Service"

