name: Aplicação - CI/CD

on:
  push:
    branches:
      - main
      - feature-flask-app

jobs:
  remote-pipeline:
    uses: Nicolascf/shared-libraries/.github/workflows/flask-app-ci-cd.yml@feature-pipeline  # Chama a Golden Pipeline
    with:
      service_name: "Flask-App-Service"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
